# how does anyone still use cURL
brew "httpie"

# how does anyone still use ls -r
brew "tree"

# life with ruby
brew "rbenv"
brew "ruby-build"

# life with javascript
brew "yarn"

# i have a weakness
brew "ne"
